### ISSUE TITLE
Improve force delete and find a way to show what table is still connected

### ISSUE THREAD

**Issue by shahryarjb** [mishka-group/mishka_developer_tools#9]
```elixir
[debug] QUERY OK source="blog_tags_mappers" db=0.5ms
DELETE FROM "blog_tags_mappers" AS b0 WHERE (b0."post_id" = $1) [<<151, 245, 17, 82, 205, 158, 76, 43, 136, 226, 61, 225, 170, 54, 20, 158>>]
[debug] QUERY ERROR db=2.0ms
DELETE FROM "blog_posts" WHERE "id" = $1 [<<151, 245, 17, 82, 205, 158, 76, 43, 136, 226, 61, 225, 170, 54, 20, 158>>]
[debug] QUERY OK db=0.1ms
rollback []
** (Ecto.ConstraintError) constraint error when attempting to delete struct:

    * blog_likes_post_id_fkey (foreign_key_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `foreign_key_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset has not defined any constraint.

    (ecto 3.7.2) lib/ecto/repo/schema.ex:783: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir 1.13.2) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto 3.7.2) lib/ecto/repo/schema.ex:768: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto 3.7.2) lib/ecto/repo/schema.ex:749: Ecto.Repo.Schema.apply/4
    (ecto 3.7.2) lib/ecto/repo/schema.ex:542: anonymous fn/10 in Ecto.Repo.Schema.do_delete/4
    (ecto 3.7.2) lib/ecto/repo/schema.ex:985: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
iex(5)> [info] POST /api/content/v1/delete-like-post
```

**Comment by shahryarjb** [comment]
https://elixirforum.com/t/foreign-key-constraint-cannot-handle-when-delete-is-nothing/47135/14
